name: flutter_sheet_localization_generator
description: Flutter localizations code generator from Google sheet files.
version: 3.0.1-nullsafe
homepage: https://github.com/aloisdeniel/flutter_sheet_localization

environment:
  sdk: ">=2.12.1 <3.0.0"

dependencies:
  http: ^0.13.3
  meta: ^1.3.0
  csv: ^5.0.0
  recase: ^4.0.0-nullsafety.0
  code_builder: ^4.0.0
  source_gen: ^1.0.0
  flutter_sheet_localization: 
      path: ../flutter_sheet_localization
  build: ^2.0.1
  analyzer: ^1.5.0
  collection: ^1.15.0

dev_dependencies:
  build_test: ^2.1.0
  build_runner: ^2.0.2
