name: flutter_sheet_localization_generator
description: Flutter localizations code generator from Google sheet files.
version: 3.0.1-nullsafe
homepage: https://github.com/aloisdeniel/flutter_sheet_localization

environment:
  sdk: ">=2.12.1 <3.0.0"

dependencies:
  http: ^0.13.0
  meta: ^1.3.0
  csv: ^5.0.0
  recase: ^4.0.0-nullsafety.0
  code_builder: ^3.7.0
  source_gen: ^0.9.10+4
  flutter_sheet_localization: 
    git:
      url: git://github.com/Dokotela/flutter_sheet_localization.git
      path: flutter_sheet_localization
  build: ^2.0.0
  analyzer: ^1.2.0
  collection: ^1.15.0

dev_dependencies:
  build_test: ^2.0.0
  build_runner: ^1.0.0
